version: "3.9"
services:
  python-repo-template:
    volumes:
      - type: volume
        source: vscode-extensions
        target: /root/.vscode-server/extensions
      - type: volume
        source: vscode-extensions-insiders
        target: /root/.vscode-server-insiders/extensions
      - type: bind
        source: ~/.config/gh
        target: /home/econ/.config/gh
        read_only: true
      # - vscode-extensions:/root/.vscode-server/extensions
      # - vscode-extensions-insiders:/root/.vscode-server-insiders/extensions
      # - ~/.config/gh:/home/econ/.config/gh:ro
    command: /bin/sh -c "while sleep 1000; do :; done"

volumes:
  vscode-extensions:
    name: python-repo-template-vscode-extensions
  vscode-extensions-insiders:
    name: python-repo-template-vscode-extensions-insiders
